name: Rust

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stable rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: |
        cargo fmt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "fmt" -a || exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Doc
      run: |
        cargo doc
    - name: Commit docs
      run: |
        cp -r ./target/doc /tmp
        cd /tmp/doc
        git init
        wget https://raw.githubusercontent.com/sagudev/nanojs/gh-pages/index.html
        git add .
        git remote add origin https://github.com/sagudev/nanojs.git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "doc" -a || exit 0
    - name: Push docs
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch : gh-pages
        force: true
        directory: /tmp/doc
    - name: Deploy to gh-pages 
      run: |
        curl -X POST https://api.github.com/repos/sagudev/nanojs/pages/builds -H "Accept: application/vnd.github.mister-fantastic-preview+json" -u sagudev:${{ secrets.GH_TOKEN }}
    - name: Clippy check
      uses: actions-rs/clippy-check@annotations-fallback
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --verbose
